# elasticsearch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data" ]
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          securityContext:
            privileged: true
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "6Gi"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: es-backup
              mountPath: /data/es_snapshot_repository
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
#            - name: s3-mount-point
#              mountPath: /mnt/s3_mount
          env:
            - name: discovery.type
              value: single-node
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: password
            # S3 配置
            - name: S3_CLIENT_DEFAULT_REGION
              value: "ap-northeast-1"
            - name: S3_CLIENT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: S3_CLIENT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
          lifecycle:
              postStart:
                exec:
                  command:
                    - "sh"
                    - "-c"
                    - |
                      echo ${S3_CLIENT_ACCESS_KEY} | /usr/share/elasticsearch/bin/elasticsearch-keystore add s3.client.default.access_key --stdin
                      echo ${S3_CLIENT_SECRET_KEY} | /usr/share/elasticsearch/bin/elasticsearch-keystore add s3.client.default.secret_key --stdin 
                      /usr/share/elasticsearch/bin/elasticsearch-plugin list | grep -q repository-s3 || /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch repository-s3
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-pvc
        - name: es-backup
          persistentVolumeClaim:
            claimName: es-backup-pvc
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
#        - name: s3-mount-point
#          emptyDir: {}

---
# Elasticsearch Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.license.self_generated.type: basic
    network.host: 0.0.0.0
    path.repo: ["/data/es_snapshot_repository"]
    s3.client.default.endpoint: "s3.ap-northeast-1.amazonaws.com"
    s3.client.default.protocol: https
    s3.client.default.read_timeout: 50s
    s3.client.default.max_retries: 3
    s3.client.default.use_throttle_retries: true
---
# Elasticsearch Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: do-block-storage-retain

---
# Elasticsearch Snapshot Repository Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: do-block-storage-retain

---
# Elasticsearch Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - port: 9200
  selector:
    app: elasticsearch
