apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcoin-indexer-repair-deployment
  namespace: starcoin-barnard
  labels:
    app: starcoin-indexer-repair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-indexer-repair
  template:
    metadata:
      labels:
        app: starcoin-indexer-repair
    spec:
      containers:
        - name: starcoin-indexer-repair
          image: starcoin/starcoin_indexer:sha-e7187a8
          ports:
            - containerPort: 8300
          env:
            - name: HOSTS
              value: "barnard5.seed.starcoin.org"
            - name: NETWORK
              value: "barnard.0727"
            - name: BG_TASK_JOBS
              value: ""
            - name: BULK_SIZE
              value: "80"
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-pw-elastic
                  key: password
            - name: STARCOIN_ES_URL
              value: "search-starcoin-es2-47avtmhexhbg7qtynzebcnnu64.ap-northeast-1.es.amazonaws.com"
            - name: STARCOIN_ES_PROTOCOL
              value: "https"
            - name: STARCOIN_ES_PORT
              value: "443"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: SWAP_API_URL
              value: "https://swap-api.starcoin.org"
            - name: SWAP_CONTRACT_ADDR
              value: "0xbd7e8be8fae9f60f2f5136433e36a091"
            - name: DS_URL
              value: "jdbc:postgresql://starcoin-pg.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com/starcoin"
            - name: DB_USER_NAME
              value: "starcoin"
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql-starcoin-yu
                  key: password
            - name: DB_SCHEMA
              value: "barnard"
            - name: PROGRAM_ARGS
              value: "auto_repair 2869980"
