apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcoin-indexer-stcscan-deployment
  namespace: starcoin-barnard
  labels:
    app: starcoin-indexer-stcscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-indexer-stcscan
  template:
    metadata:
      labels:
        app: starcoin-indexer-stcscan
    spec:
      containers:
        - name: starcoin-indexer-stcscan
          image: starcoin/starcoin_indexer:sha-1223fc3
          ports:
            - containerPort: 8300
          env:
            - name: HOSTS
              value: "barnard.seed.starcoin.org"
            - name: NETWORK
              value: "barnard.0727"
            - name: BG_TASK_JOBS
              value: "indexer,secondary,market_cap,txn_payload"
            - name: TXN_OFFSET
              value: "0"
            - name: BULK_SIZE
              value: "80"
            - name: STARCOIN_ES_URL
              value: "10.104.0.12"
            - name: STARCOIN_ES_PROTOCOL
              value: "https"
            - name: STARCOIN_ES_PORT
              value: "9200"
            - name: STARCOIN_ES_USER
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: username
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: password
            - name: ELASTICSEARCH_TRUSTSTORE_PATH
              value: "/etc/elasticsearch/cert/truststore.jks"
            - name: SWAP_API_URL
              value: "https://swap-api.starswap.xyz"
            - name: SWAP_CONTRACT_ADDR
              value: "0xbd7e8be8fae9f60f2f5136433e36a091"
            - name: DS_URL
              value: "jdbc:postgresql://private-db-postgresql-sgp1-29237-do-user-13054015-0.h.db.ondigitalocean.com:25060/starcoin"
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: DB_SCHEMA
              value: "barnard"
            - name: PROGRAM_ARGS
              value: ""
          volumeMounts:
            - name: es-cert-volume
              mountPath: /etc/elasticsearch/cert
              readOnly: true
      volumes:
        - name: es-cert-volume
          secret:
            secretName: es-truststore-secret
            items:
              - key: truststore.jks
                path: truststore.jks