apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcoin-indexer-stcscan-deployment
  namespace: starcoin-vega
  labels:
    app: starcoin-indexer-stcscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-indexer-stcscan
  template:
    metadata:
      labels:
        app: starcoin-indexer-stcscan
    spec:
      containers:
        - name: starcoin-indexer-stcscan
          image: starcoin/starcoin_indexer:dag_inspector_vega_6
          ports:
            - containerPort: 8300
          env:
            - name: HOSTS
              value: "vega.seed.starcoin.org"
            - name: NETWORK
              value: "vega.0727"
            - name: BG_TASK_JOBS
              value: "indexer,secondary,market_cap,txn_payload,swap_stats,txn_global_idx_update"
            - name: BULK_SIZE
              value: "100"
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: password
            - name: STARCOIN_ES_URL
              value: "elasticsearch.default.svc.cluster.local"
            - name: TXN_OFFSET
              value: "0"
            - name: STARCOIN_ES_PROTOCOL
              value: "http"
            - name: STARCOIN_ES_PORT
              value: "9200"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: SWAP_API_URL
              value: "https://swap-api.starswap.xyz"
            - name: SWAP_CONTRACT_ADDR
              value: "0xbd7e8be8fae9f60f2f5136433e36a091"
            - name: DS_URL
              value: "jdbc:postgresql://private-db-postgresql-sgp1-29237-do-user-13054015-0.h.db.ondigitalocean.com:25060/starcoin"
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: DB_SCHEMA
              value: "vega"
            - name: PROGRAM_ARGS
              value: ""
          #valume:
