apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-api-deployment
  labels:
    app: scan-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan-api
  template:
    metadata:
      labels:
        app: scan-api
    spec:
      containers:
        - name: scan-api
          image: starcoin/starcoin_scan:sha-52e8d55
          ports:
            - containerPort: 8500
          env:
            - name: STARCOIN_ES_URL
              value: "123.57.40.36"
            - name: STARCOIN_ES_PROTOCOL
              value: "http"
            - name: STARCOIN_ES_PORT
              value: "9200"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: STARCOIN_ES_INDEX_VERSION
              value:
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-pw-elastic
                  key: password
            - name: DS_URL
              value: "jdbc:postgresql://123.57.40.36:8432/starcoin"
            - name: DB_USER_NAME
              value: ""
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql-pw-starcoin
                  key: password
