apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-api-deployment
  namespace: starcoin-api
  labels:
    app: scan-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan-api
  template:
    metadata:
      labels:
        app: scan-api
    spec:
      containers:
        - name: scan-api
          image: starcoin/starcoin_scan:scan_api_dag_2
          ports:
            - name: http
              containerPort: 8500
            - name: multicast
              containerPort: 5701
          env:
            - name: STARCOIN_ES_URL
              value: "elasticsearch.default.svc.cluster.local"
            - name: STARCOIN_ES_PROTOCOL
              value: "http"
            - name: STARCOIN_ES_PORT
              value: "9200"
            - name: STARCOIN_ES_USER
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: username
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: password
            - name: STARCOIN_ES_INDEX_VERSION
              value: ".0727"
            - name: DS_URL
              value: "jdbc:postgresql://private-db-postgresql-sgp1-29237-do-user-13054015-0.h.db.ondigitalocean.com:25060/starcoin"
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            # Maybe useless variables
            - name: MAIN_DS_URL
              value: "jdbc:postgresql://private-db-postgresql-sgp1-29237-do-user-13054015-0.h.db.ondigitalocean.com:25060/starcoin?currentSchema=main"
            - name: BARNARD_DS_URL
              value: "jdbc:postgresql://private-db-postgresql-sgp1-29237-do-user-13054015-0.h.db.ondigitalocean.com:25060/starcoin?currentSchema=barnard"
            - name: HALLEY_DS_URL
              value: "jdbc:postgresql://private-db-postgresql-sgp1-29237-do-user-13054015-0.h.db.ondigitalocean.com:25060/starcoin?currentSchema=halley"
            - name: STARCOIN_USER_DS_URL
              value: "jdbc:postgresql://private-db-postgresql-sgp1-29237-do-user-13054015-0.h.db.ondigitalocean.com:25060/starcoin?currentSchema=starcoin_user"

