apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-api-deployment
  namespace: starcoin-api
  labels:
    app: scan-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan-api
  template:
    metadata:
      labels:
        app: scan-api
    spec:
      containers:
        - name: scan-api
          image: starcoin/starcoin_scan:sha-1223fc3
          ports:
            - name: http
              containerPort: 8500
            - name: multicast
              containerPort: 5701
          env:
            - name: STARCOIN_ES_URL
              value: "elasticsearch.default.svc.cluster.local"
            - name: STARCOIN_ES_PROTOCOL
              value: "http"
            - name: STARCOIN_ES_PORT
              value: "9200"
            - name: STARCOIN_ES_USER
              value: elastic
            - name: STARCOIN_ES_INDEX_VERSION
              value: ".0727"
            - name: STARCOIN_ES_PWD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: password
            - name: DS_URL
              value: "jdbc:postgresql://postgres-service.default.svc.cluster.local/starcoin"
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: username
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password

