apiVersion: v1
kind: Service
metadata:
  labels:
    app: scan-api
  name: hazelcast-service
  namespace: starcoin-api
spec:
  selector:
    app: scan-api
  ports:
    - name: multicast
      port: 5701
  type: LoadBalancer