# This composer file is used to configure the local environment for debugging
version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  hazelcast:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast
    ports:
      - "5701:5701"
    environment:
      - HZ_CLUSTERNAME=stcscan-hazelcast-cluster
      - HZ_NETWORK_JOIN_MULTICAST_ENABLED=false
      - HZ_NETWORK_JOIN_TCPIP_ENABLED=true
      - HZ_NETWORK_JOIN_TCPIP_MEMBERS=hazelcast
      - HZ_CACHE_CODE_CACHE_STATISTICS_ENABLED=true
      - HZ_CACHE_CODE_CACHE_EVICTION_SIZE=10000
      - HZ_CACHE_CODE_CACHE_EVICTION_MAX_SIZE_POLICY=ENTRY_COUNT
      - HZ_CACHE_CODE_CACHE_EVICTION_EVICTION_POLICY=LFU
      - HZ_CACHE_SESSION_STATISTICS_ENABLED=true
      - HZ_CACHE_SESSION_EVICTION_SIZE=50000
      - HZ_CACHE_SESSION_EVICTION_MAX_SIZE_POLICY=ENTRY_COUNT
      - HZ_CACHE_SESSION_EVICTION_EVICTION_POLICY=LRU

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  postgresql:
    image: postgres:13.2
    container_name: postgres_db
    environment:
      POSTGRES_USER: starcoin
      POSTGRES_PASSWORD: starcoin
      POSTGRES_DB: starcoin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  esdata:
    driver: local
