# Elasticsearch Snapshot Repository Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-backup1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 90Gi
  storageClassName: do-block-storage-retain